[workspace]

members = [
    "controller",
    "hyperactor",
    "hyperactor_macros",
    "hyperactor_multiprocess",
    "hyperactor_mesh",
    "hyperactor_mesh_macros",
    "ndslice",
    "monarch_extension",
    "monarch_worker",
    "nccl-sys",
    "torch-sys",
]
