[workspace]
resolver = "2"
members = [
    "controller",
    "cuda-sys",
    "hyper",
    "hyperactor",
    "hyperactor_macros",
    "hyperactor_multiprocess",
    "hyperactor_mesh",
    "hyperactor_mesh_macros",
    "ndslice",
    "monarch_extension",
    "monarch_tensor_worker",
    "nccl-sys",
    "rdmacore-sys",
    "torch-sys",
]
