[book]
authors = ["Shayne Fletcher"]
language = "en"
src = "src"
title = "Hyperactor Book"

[output.html]
git-repository-url = "https://github.com/meta-pytorch/monarch"
edit-url-template = "https://github.com/meta-pytorch/monarch/edit/main/books/hyperactor-book/src/{path}"
