name: CI

on:
  pull_request:
    branches:
      - main
      - gh/**
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  build-cuda:
    name: Build CUDA
    uses: ./.github/workflows/build-cuda.yml

  build-cpu:
    name: Build CPU
    uses: ./.github/workflows/build-cpu.yml

  test-cuda:
    name: Test CUDA
    needs: build-cuda
    uses: ./.github/workflows/test-cuda.yml
    with:
      artifact-name: monarch-cuda-${{ github.sha }}

  test-cpu:
    name: Test CPU
    needs: build-cpu
    uses: ./.github/workflows/test-cpu.yml
    with:
      artifact-name: monarch-cpu-${{ github.sha }}

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [test-cuda, test-cpu]
    if: always()
    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ needs.test-cuda.result }}" != "success" ]] ||
             [[ "${{ needs.test-cpu.result }}" != "success" ]]; then
            echo "One or more jobs failed"
            exit 1
          else
            echo "All jobs passed"
          fi
