name: Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          set -eux
          pip install --upgrade pip
          pip install -r build-requirements.txt

          # Skip building the Python package for documentation purposes
          # This avoids the Rust build issues
          # pip install --no-build-isolation .

          pip install -r docs/requirements.txt

      - name: Generate Rust API Documentation
        run: |
          set -eux
          # Set required environment variables for Rust documentation generation
          export RUSTFLAGS="-Zthreads=16"
          export _GLIBCXX_USE_CXX11_ABI=1

          # Generate documentation for all crates in the workspace with nightly features
          cargo +nightly doc --workspace --no-deps

          # Create an index.html file in the target/doc directory to serve as the main entry point
          echo '<meta http-equiv="refresh" content="0; url=help.html">' > target/doc/index.html

          # Ensure the target/doc directory exists in the expected location for Sphinx
          mkdir -p docs/source/target
          cp -r target/doc docs/source/target/

      - name: Build Sphinx Docs
        working-directory: docs
        run: |
          set -eux

          make html
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
